### ISSUE TITLE
Probleme de creation d'arbre

### ISSUE THREAD

**Issue by pouet** [ThomasSan/42sh#19]
Quand je fais ça `ls | wc && cat` le cat n'est pas exécuté, enfin, il l'est peut être mais c'est que l'entrée standard est fermée !
Problême de creation d'arbre je pense ! Le && ne doit pas être après le pipe mais 'au-dessus'. ;)

**Comment by baldychristophe** [comment]
c'etait un probleme de stdin fermé, c'est reglé sur mon fork je le mets a jour sur la branche principale après
