### ISSUE TITLE
t_token type dans le cas d'une redirection <

### ISSUE THREAD

**Issue by baldychristophe** [ThomasSan/42sh#27]
quand on ecrit: 
"1  < filename"  -> '1' est considéré comme un t_token de type WORDS, mais quand on ecrit:
"1< filename" -> (sans espace entre '1' et '<') '1' est aussi considéré comme un t_token de type WORDS alors qu'il devrait etre consideré comme un type NUMBERS.

**Comment by ThomasSan** [comment]
Problem Solved
