### ISSUE TITLE
Fermeture de FD

### ISSUE THREAD

**Issue by pouet** [ThomasSan/42sh#54]
Il doit y avoir un problème sur le fd fermé :

`:> cat 1>&-
cat 1>&-
cat: stdin: Bad file descriptor
:> cat 0>&-
cat 0>&-
cat: stdin: Bad file descriptor`

Sur le premier je devrais fermer stdout.

**Comment by baldychristophe** [comment]
je ne comprends pas ou est le problème, je reproduis exactement ce qu'il se passe sur bash...

**Comment by baldychristophe** [comment]
probleme resolu
