### ISSUE TITLE
echo "wdla" | cat 

### ISSUE THREAD

**Issue by dbaldy** [ThomasSan/42sh#70]

**Comment by baldychristophe** [comment]
c'est un probleme sur la gestion des quotes dans le lexer:
il ne detecte pas la fermeture de la quote et fait comme si tu avais ecris:
echo "wdla | cat"

**Comment by baldychristophe** [comment]
probleme resolu
J'ai fait des légères modifs sur deux fonctions du lexer:
join_quoted
return_type_quoted
